//This software is licensed under the GNU GPL v3
//Written by William Seymour

package mcnutty.music.get;

class QueueItem {

    private String diskName;
    private String realName;
    private String ip;

    QueueItem(String diskName, String realName, String ip) {
        this.diskName = diskName;
        this.realName = realName;
        this.ip = ip;
    }

    QueueItem() {
        this.diskName = null;
        this.realName = null;
        this.ip = null;
    }

    public String getDiskName() {
        return diskName;
    }

    public String getRealName() {
        return realName;
    }

    public String getIp() {
        return ip;
    }

    /**
     * Autogenerated by IntelliJ IDEA - regenerate when class is modified
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        final QueueItem queueItem = (QueueItem) o;

        if (diskName != null ? !diskName.equals(queueItem.diskName) : queueItem.diskName != null) return false;
        if (realName != null ? !realName.equals(queueItem.realName) : queueItem.realName != null) return false;
        return ip != null ? ip.equals(queueItem.ip) : queueItem.ip == null;
    }

    /**
     * Autogenerated by IntelliJ IDEA - regenerate when class is modified
     */
    @Override
    public int hashCode() {
        int result = diskName != null ? diskName.hashCode() : 0;
        result = 31 * result + (realName != null ? realName.hashCode() : 0);
        result = 31 * result + (ip != null ? ip.hashCode() : 0);
        return result;
    }
}
